version: '3'

services:
  mysql_db:
    image: mysql:latest
    mem_limit: '1g'
    mem_reservation: '512m'
    # cpus: '1'
    # cpuset: '2'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data: